
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/mateusz/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 6.2.15-100.fc36.x86_64 - x86_64
...
